"""empty message

Revision ID: 2e5988839eee
Revises: cb10c24c4f02
Create Date: 2019-09-26 18:04:51.279798

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2e5988839eee'
down_revision = 'cb10c24c4f02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('query',
    sa.Column('query_id', sa.Integer(), nullable=False),
    sa.Column('query_string', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('execution_status', sa.SMALLINT(), nullable=False),
    sa.Column('db_connection_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('query_result', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['db_connection_id'], ['db_connection.db_connection_id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.project_id'], ),
    sa.PrimaryKeyConstraint('query_id')
    )
    op.create_index(op.f('ix_query_db_connection_id'), 'query', ['db_connection_id'], unique=False)
    op.create_index(op.f('ix_query_project_id'), 'query', ['project_id'], unique=False)
    op.add_column('organization', sa.Column('org_description', sa.Text(), nullable=True))
    op.add_column('project', sa.Column('project_description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'project_description')
    op.drop_column('organization', 'org_description')
    op.drop_index(op.f('ix_query_project_id'), table_name='query')
    op.drop_index(op.f('ix_query_db_connection_id'), table_name='query')
    op.drop_table('query')
    # ### end Alembic commands ###
