"""Added JSON Column in user table

Revision ID: b53455ca6852
Revises: 2e5988839eee
Create Date: 2019-10-18 16:10:18.751942

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b53455ca6852'
down_revision = '2e5988839eee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user',
                  sa.Column('asset', postgresql.JSON(astext_type=sa.Text()),
                            nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'asset')
    # ### end Alembic commands ###
