"""empty message

Revision ID: cb10c24c4f02
Revises: 50af0a95126f
Create Date: 2019-09-13 15:26:13.384667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb10c24c4f02'
down_revision = '50af0a95126f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personal_token', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.alter_column('test_suite', 'excel_name',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('test_suite', 'excel_name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('personal_token', 'is_deleted')
    # ### end Alembic commands ###
